
function fft_core_config(this_block)

  % Revision History:
  %
  %   10-Dec-2015  (15:12 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/oxygen26/TMADDEN/ROACH2/projcts/fft_core.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('fft_core');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('pol1');
  this_block.addSimulinkInport('pol2');
  this_block.addSimulinkInport('pol3');
  this_block.addSimulinkInport('pol4');
  this_block.addSimulinkInport('shift');
  this_block.addSimulinkInport('sync');

  this_block.addSimulinkOutport('of_x0');
  this_block.addSimulinkOutport('out0');
  this_block.addSimulinkOutport('out1');
  this_block.addSimulinkOutport('out2');
  this_block.addSimulinkOutport('out3');
  this_block.addSimulinkOutport('sync_out');

  of_x0_port = this_block.port('of_x0');
  of_x0_port.setType('UFix_2_0');
  out0_port = this_block.port('out0');
  out0_port.setType('UFix_36_0');
  out1_port = this_block.port('out1');
  out1_port.setType('UFix_36_0');
  out2_port = this_block.port('out2');
  out2_port.setType('UFix_36_0');
  out3_port = this_block.port('out3');
  out3_port.setType('UFix_36_0');
  sync_out_port = this_block.port('sync_out');
  sync_out_port.setType('Bool');
  sync_out_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('pol1').width ~= 36);
      this_block.setError('Input data type for port "pol1" must have width=36.');
    end

    if (this_block.port('pol2').width ~= 36);
      this_block.setError('Input data type for port "pol2" must have width=36.');
    end

    if (this_block.port('pol3').width ~= 36);
      this_block.setError('Input data type for port "pol3" must have width=36.');
    end

    if (this_block.port('pol4').width ~= 36);
      this_block.setError('Input data type for port "pol4" must have width=36.');
    end

    if (this_block.port('shift').width ~= 9);
      this_block.setError('Input data type for port "shift" must have width=9.');
    end

    if (this_block.port('sync').width ~= 1);
      this_block.setError('Input data type for port "sync" must have width=1.');
    end

    this_block.port('sync').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk_1','ce_1')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('fft_core.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

